FROM ubuntu:14.04

# Set locales
RUN locale-gen en_GB.UTF-8
ENV LANG en_GB.UTF-8
ENV LC_CTYPE en_GB.UTF-8

# Fix sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Install dependencies

RUN \
sed -i 's#http://archive.ubuntu.com#http://cn.archive.ubuntu.com#g' /etc/apt/sources.list  && \
apt-get update ; \
apt-get install -y build-essential curl wget 

#install fizsh 
RUN apt-get  install -y fizsh man lrzsz 

CMD ["/usr/bin/fizsh"]
