package my.dao.mybatis.mi;

import my.dao.mybatis.Mapper;
import my.model.b_example.AppUserExample;
import my.model.persist.User;
import my.model.persist.project.Role;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

//@.formatter:off
public interface AppUserMapper extends Mapper {

	void insertRoles(@Param("roles") Set roles, @Param("userId") Long userId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int countByExample(AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int deleteByExample(AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	List<User> selectByExample(AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	User selectByPrimaryKey(Long id);

	Set<Role> selectRoles(@Param("userId") Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") User record, @Param("example") AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") AppUserExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_user
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(User record);
}
