package my.dao.mybatis.mi;

import my.dao.mybatis.Mapper;
import my.model.b_example.FavourExample;
import my.model.persist.board.Favour;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FavourMapper extends Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int countByExample(FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int deleteByExample(FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int insert(Favour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int insertSelective(Favour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    List<Favour> selectByExampleWithBLOBs(FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    List<Favour> selectByExample(FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    Favour selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Favour record, @Param("example") FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Favour record, @Param("example") FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Favour record, @Param("example") FavourExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Favour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Favour record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favour
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Favour record);
}
