package my.dao.mybatis.mi;

import my.dao.mybatis.Mapper;
import my.model.b_example.MoundExample;
import my.model.persist.spirit.Mound;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MoundMapper extends Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int countByExample(MoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int deleteByExample(MoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int insert(Mound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int insertSelective(Mound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    List<Mound> selectByExampleWithBLOBs(MoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    List<Mound> selectByExample(MoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    Mound selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Mound record, @Param("example") MoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Mound record, @Param("example") MoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Mound record, @Param("example") MoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Mound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mound
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mound record);
}
