package my.dao.mybatis.mi;

import my.dao.mybatis.Mapper;
import my.model.b_example.PrayExample;
import my.model.persist.project.Pray;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PrayMapper extends Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int countByExample(PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int deleteByExample(PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int insert(Pray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int insertSelective(Pray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    List<Pray> selectByExampleWithBLOBs(PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    List<Pray> selectByExample(PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    Pray selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Pray record, @Param("example") PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Pray record, @Param("example") PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Pray record, @Param("example") PrayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Pray record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pray
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pray record);
}
