package my.dao.mybatis.mi;

import my.dao.mybatis.Mapper;
import my.model.b_example.SettingExample;
import my.model.persist.Setting;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SettingMapper extends Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int countByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int deleteByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int insertSelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    List<Setting> selectByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    Setting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Setting record);
}
