package my.dao.mybatis.mi;

import my.dao.mybatis.Mapper;
import my.model.b_example.StoneExample;
import my.model.persist.spirit.Stone;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StoneMapper extends Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int countByExample(StoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int deleteByExample(StoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int insert(Stone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int insertSelective(Stone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    List<Stone> selectByExampleWithBLOBs(StoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    List<Stone> selectByExample(StoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    Stone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Stone record, @Param("example") StoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Stone record, @Param("example") StoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Stone record, @Param("example") StoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Stone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Stone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stone
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Stone record);
}
